### ISSUE TITLE
The scene breaks due to 'setMode_' in game.js

### ISSUE THREAD

**Issue by juniorxsound** [Avnerus/tzina#11]
Hi @Avnerus I added in the linesMaterial back in _video_rgbd.js_ but am unable to load the scene, it breaks due to:
`game.js:262 Uncaught TypeError: Cannot read property 'setMode_' of undefined`

Plus if your checking it out, how do I add a test character into the scene?

**Comment by Avnerus** [comment]
Hi! A problem occurred recently in which errors that happen during loading are not printed (get lost in some thread) and instead you will see the above error. Sorry for that, hopefully will get a chance to debug that soon.
Until then, try removing some of the code you added until it works again, and then check. Probably it's just some syntax error in the code you added.

To add a character:

1. Add it to *characters.js*
2. Add it in the *characters* property of one of the chapters in *chapters.js*
3. You can jump to that chapter in *game.js*. Look for this code
`            this.timeController.transitionTo(17,1); 
`

**Comment by juniorxsound** [comment]
Thanks man! I'll try this and let you know if I hit a dead end

**Comment by juniorxsound** [comment]
Hi @Avnerus seems it was actually a syntax error, thanks (i'll just use linter for now), the wire engine is back in, plus I did change the scene to 17 but am still not seeing any character

**Comment by Avnerus** [comment]
Hmm and everything is set correctly in *characters.js* and *chapters.js* with matching names? Also make sure the assets are placed correctly with the convention:  
```
assets/characters/NAME_idle.webm
assets/characters/NAME_full.webm
assets/characters/NAME_subtitles.webm
```
